### ISSUE TITLE
Tables in reports

### ISSUE THREAD

**Issue by vkhemani** [mahendrapaipuri/grafana-dashboard-reporter-app#103]
hi,

(reopening the issue raised earlier on tables)
Reports with tables are asked by end users for sending to various parties like customers, auditors, quality check etc. usually hourly, daily reports, monthly reports are required. If possible limit the no. of pages in pdf to 5 or 10..

**Comment by mahendrapaipuri** [comment]
Hey, Thanks for reopening this issue. I will see what I can do.

**Comment by vkhemani** [comment]
Hi. any development on this issue?

**Comment by mahendrapaipuri** [comment]
Hey there, I am quite busy with some other projects at the moment and I will try to come back to it as soon as I can. It is on my list!!

**Comment by mahendrapaipuri** [comment]
@vkhemani Could you please try #120 and see if it works for your usecase?
