### ISSUE TITLE
Plugin does not work with Grafana v11.3.0

### ISSUE THREAD

**Issue by wulfchr** [mahendrapaipuri/grafana-dashboard-reporter-app#146]
I have successfully installed the plugin and it seems to be working. A PDF file is created, but the panels are not displayed. Error is "Panel not found". What is the error? Are there log files with error messages?

example:
http://10.10.1.15:3000/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=ee114x37eymf4a
[MKK-Klimaldaten.pdf](https://github.com/user-attachments/files/17521196/MKK-Klimaldaten.pdf)

Thank you for the help

**Comment by mahendrapaipuri** [comment]
Hey @wulfchr, Did you install [grafana-image-renderer](https://github.com/grafana/grafana-image-renderer) plugin too? That plugin is a prerequisite to the current reporter plugin.

Could you please turn on debug mode on Grafana server and post the logs here? Without logs it is very hard to find the root cause.

Cheers

**Comment by wulfchr** [comment]
Hey @mahendrapaipuri , I have installed the grafana-image-renderer plugin. The graphics output works without any problems. The log file is attached. I created a new dashboard again and tested the PDF export. Unfortunately also without success.
![ee1wt4lp1rmkgf](https://github.com/user-attachments/assets/fe0610cc-5fb3-46f4-bc28-f39e00491181)
![Grafana Image Renderer - Plug-ins](https://github.com/user-attachments/assets/37ebcdfa-1478-44ab-b2be-655d3ed00ee2)
[Grafana-Log1.txt](https://github.com/user-attachments/files/17526824/Grafana-Log1.txt)

Thank you for the help

**Comment by mahendrapaipuri** [comment]
Hey thanks for the details. However, you tailed the logs. Can you please post full logs right from the restart of Grafana server, make a request to generate report and wait until report generation request finished? 

Thanks!

**Comment by wulfchr** [comment]
Hey @mahendrapaipuri , I have stop the grafana-server, then delete the old log file grafana.log, then start the grafana-server and make a report (http://10.10.1.15:3000/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=ee114x37eymf4a)  than i load the grafana.log.

![Grafana Dashboard Report](https://github.com/user-attachments/assets/6fcaf01f-91bb-4c0c-b8d9-95cdf962b405)
[grafana.log](https://github.com/user-attachments/files/17528086/grafana.log)

Thank you for the help

**Comment by mahendrapaipuri** [comment]
Thanks a lot for the comprehensive logs @wulfchr those are very useful. I see there are few errors from `chromium`. I will try to reproduce it. Can you try generating the report using this [basic dashboard](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/dashboards/test-dashboard-collapsed.json) on your instance? And is it possible to share your dashboard JSON model?

**Comment by wulfchr** [comment]
Many thanks for your support. I imported your dashboard and created a report. The result is the same as before. Attached is a graphic and the new log file and the json file of dashboard.
![Grafana Dashboard Report](https://github.com/user-attachments/assets/eb587da8-a0a1-4359-bea2-80a6c763a4d8)
[grafana.log](https://github.com/user-attachments/files/17529949/grafana.log)
[SHLM-Klimasensor-001-1729937850570.json](https://github.com/user-attachments/files/17529951/SHLM-Klimasensor-001-1729937850570.json)

Thank you for the help

**Comment by mahendrapaipuri** [comment]
Thanks a lot @wulfchr  for your tests. I confirm this behaviour in the latest Grafana `v11.3.0`.  The plugin needs some changes to work with Grafana `v11.3.0`. I will work on it.

In the mean time, if it is not a hassle for you, you can downgrade to Grafana `v11.2.0` and the reporter plugin should work without any issues.

Thanks a lot for reporting this issue.

**Comment by J-Paul0815** [comment]
> Thanks a lot @wulfchr for your tests. I confirm this behaviour in the latest Grafana `v11.3.0`. The plugin needs some changes to work with Grafana `v11.3.0`. I will work on it.
> 
> In the mean time, if it is not a hassle for you, you can downgrade to Grafana `v11.2.0` and the reporter plugin should work without any issues.

@mahendrapaipuri 
Thanks for caring. I can confirm that the problems starts after a Grafana update from 11.2.2 to 11.3.0. However, unlike Wulf, I get a "Permission denied" error and not an empty PDF.

**Comment by wulfchr** [comment]
Thank you @mahendrapaipuri for your efforts and the info. Since I can't estimate how much programming effort you need, I'll downgrade to version 11.2.0 first. Or is it worth waiting? Best regards, Wulf

**Comment by mahendrapaipuri** [comment]
I am looking at the necessary changes. I will try to put up a PR so that you can test it on your deployments. It helps as well to test the plugin in real cases. If it is ok for you to wait for couple of days, I will manage to do a PR.

@J-Paul0815 Thanks for the feedback. #147 fixes the permission denied error. Anyways if you are on Grafana v11.3.0, you are blocked as the plugin needs update.

**Comment by wulfchr** [comment]
Hello @mahendra,Thank you very much for your quick efforts. I will gladly wait and test when you are ready with the programming.Best regardsWulfAm 29.10.2024 um 09:12 schrieb Mahendra Paipuri ***@***.***>:﻿
I am looking at the necessary changes. I will try to put up a PR so that you can test it on your deployments. It helps as well to test the plugin in real cases. If it is ok for you to wait for couple of days, I will manage to do a PR.
@J-Paul0815 Thanks for the feedback. #147 fixes the permission denied error. Anyways if you are on Grafana v11.3.0, you are blocked as the plugin needs update.

**Comment by J-Paul0815** [comment]
> I am looking at the necessary changes. I will try to put up a PR so that you can test it on your deployments. It helps as well to test the plugin in real cases. If it is ok for you to wait for couple of days, I will manage to do a PR.
> 
> @J-Paul0815 Thanks for the feedback. #147 fixes the permission denied error. Anyways if you are on Grafana v11.3.0, you are blocked as the plugin needs update.

Hi Mahendra, I'm back on Grafana v11.2.2 for now and in my case it's (still) a test system. If I can test something, provide logs, or provide any other support, please let me know.

**Comment by mahendrapaipuri** [comment]
Cheers @J-Paul0815 I have put up a PR and tagged you there. If you could test that PR, it would be of great help!

Cheers
