### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by SanthoshKumar18245** [mahendrapaipuri/grafana-dashboard-reporter-app#15]
NFO [03-29|05:42:52] Request Completed logger=context userId=0 orgId=0 uname= method=GET path=/render/d-solo/rYdddlPWk/_ status=302 remote_addr=127.0.0.1 time_ms=1 duration=1.197513ms size=47 referer= handler=/render/* status_source=server
INFO [03-29|05:42:52] Request Completed logger=context userId=0 orgId=0 uname= method=GET path=/user/auth-tokens/rotate status=302 remote_addr=127.0.0.1 time_ms=9 duration=9.874658ms size=24 referer="http://localhost:3000/render/d-solo/rYdddlPWk/_?from=now-1h&height=500&panelId=37&theme=light&to=now&width=1000" handler=/user/auth-tokens/rotate status_source=server
WARN [03-29|05:42:52] Failed to authenticate request logger=authn.service client=auth.client.session error="user token not found"
INFO [03-29|05:42:52] Request Completed logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=127.0.0.1 time_ms=2 duration=2.61458ms size=29 referer=http://localhost:3000/user/auth-tokens/rotate handler=/ status_source=server
WARN [03-29|05:42:52] Failed to authenticate request logger=authn.service client=auth.client.session error="user token not found"
WARN [03-29|05:42:52] Failed to authenticate request logger=authn.service client=auth.client.session error="user token not found"
INFO [03-29|05:42:52] Request Completed logger=context userId=0 orgId=0 uname= method=GET path=/render/d-solo/rYdddlPWk/_ status=302 remote_addr=127.0.0.1 time_ms=0 duration=990.259µs size=29 referer= handler=/render/* status_source=server
WARN [03-29|05:42:52] Failed to authenticate request logger=authn.service client=auth.client.session error="user token not found"
WARN [03-29|05:42:52] Failed to authenticate request logger=authn.service client=auth.client.session error="user token not found"

**Comment by SanthoshKumar18245** [comment]
@mahendrapaipuri @and-mora please tell me about this because i cannot find it in the documentation

**Comment by and-mora** [comment]
I need more details how you obtained it. Did you login into your Grafana server?

**Comment by mahendrapaipuri** [comment]
Sorry for the late reply. I have been away. 

The plugin forwards the user cookie to make API requests to get PNG of each panel in the dashboard. From the logs, it seems that there is an issue with forwarding this cookie. Could you check from the browser console that cookie is being set upon login?

I will need some info about your Grafana instance:

- what is the root_url you are setting in Grafana config and is it different from URL Grafana is being exposed to user?

- could you share your Grafana config? Especially the default settings that you have changed. 

Cheers!

**Comment by ObserveLite** [comment]
Apologies @mahendrapaipuri Sir,

root_url = %(protocol)s://%(domain)s:%(http_port)s/

i have changed the database sqlite to mysql that's it

**Comment by SanthoshKumar18245** [comment]
Apologies @mahendrapaipuri Sir,

root_url = %(protocol)s://%(domain)s:%(http_port)s/

i have changed the database sqlite to mysql that's it 

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/d64c8f8c-0968-452f-b43b-e3e2e7e6107b)

**Comment by mahendrapaipuri** [comment]
Could you try clearing your browser cookies and retry generating a report? Also, could you check if cookie is being properly set? 

What is the Grafana setting of `cookie_samesite`? You should be able to find it from Grafana UI.

**Comment by SanthoshKumar18245** [comment]
Greetings @mahendrapaipuri ,
 
![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/09c50a27-30c1-4a30-b5b3-59d5222b6f20)
my cookie_samesite is lax

I got Error like this !!!!

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/e7025096-4134-4638-afe3-594fed25100e)

**Comment by SanthoshKumar18245** [comment]
I downloaded the Grafana-image-Render plugin and then the issue has been solved and report generated successfully

But then I tried to get report again then i got this warning 
WARN [05-17|17:51:18] Failed to authenticate request           logger=authn.service client=auth.client.session error="user token not found"

<img width="959" alt="image" src="https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/b812c65a-63f8-4023-9871-607c1cbcc983">

my report looks like This!!!

**Comment by mahendrapaipuri** [comment]
> But then I tried to get report again then i got this warning
WARN [05-17|17:51:18] Failed to authenticate request logger=authn.service client=auth.client.session error="user token not found"

Grafana rotates cookie tokens. It can happen that the cookie token has been rotated between the moment you sent a report generation request and the API calls that plugin makes to Grafana. Just try to generate it again and it should work. 

> and can you tell me how to change the generated report pdf name as dashboard name

You mean title inside the PDF or PDF file name? They both are set to dashboard name by default.

> how to specify the time range of the dashboard to generate reports please!!!!!!

You can use query parameters `<grafanaAppUrl>/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=<UID of dashboard>&from=now-5m&to=now`

**Comment by SanthoshKumar18245** [comment]
@mahendrapaipuri Sorry!! I can't download the pdf .. ,so I don't know the pdf file name  and i try to run this on my edge browser and i got this i am hosting grafana on a different server , the plugin only on chrome ???

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/a90e09be-3c6d-4638-9ba6-9036d043646d)

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/88730aeb-3246-4c6f-96ce-873df7991e30)
Errors like this also..

**Comment by mahendrapaipuri** [comment]
This error is from headless chromium. Did you install chromium on your Grafana server? Also, these sort of errors can be transient. So retry few times after restarting Grafana server

**Comment by SanthoshKumar18245** [comment]
yes, I installed the headless chromium on my server

and can you provide me the url to run the plugin using service account api token or i we can add the api token in provisioning file ?

**Comment by mahendrapaipuri** [comment]
Please check the [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/dashmodel_from_browser/src#using-grafana-api)

**Comment by SanthoshKumar18245** [comment]
Thank you @mahendrapaipuri 

and how to change the Time zone  UTC to IST .

**Comment by mahendrapaipuri** [comment]
The current implementation picks the local time zone of Grafana server. There is a feature in pipeline to configure time zone #34
