### ISSUE TITLE
Graph times differ from datetime range

### ISSUE THREAD

**Issue by jwavoet** [mahendrapaipuri/grafana-dashboard-reporter-app#188]
When I generate a report with the default settings I get this as output:

![Scherm­afbeelding 2024-12-05 om 11 48 06](https://github.com/user-attachments/assets/83d86646-3a42-46d1-b8a9-c2df60b399c9)

When I change the timezone to Europe/Amsterdam I get this as output:

![Scherm­afbeelding 2024-12-05 om 11 50 37](https://github.com/user-attachments/assets/e3910d8f-7dc9-4bba-84c5-1d7fcdf12f38)

The datetime range in the upper right corner changes to CET, but the timings on the graph are still UTC.

Good to know, the timezone in Grafana is CET (UTC+01:00) by default.

If I set the timezone to Europe/Amsterdam in the plugin settings I get the same bug (picture 2).

I'm running Grafana 11.3.1 with the plugin version 1.7.0. Let me know if you need more information.

**Comment by mahendrapaipuri** [comment]
Cheers for reporting this issue @jwavoet 

Yes, I confirm that currently the plugin uses the time zone only to render appropriate range in the report. For the panels to be rendered in a given time zone, you will need to set it up with [Grafana image renderer config](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#rendering_timezone). So, to conclude to be able to generate reports in a given time zone:

- Configure browser time zone for [Grafana image renderer config](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#rendering_timezone)
- Configure the same time zone for the [current plugin](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#report-settings)

Could you please check if that the above solution works for you? If so, I will update the documentation.

Cheers!

**Comment by mahendrapaipuri** [comment]
Thanks for reporting it. I will add it to the docs!!
