### ISSUE TITLE
PDF export with german date

### ISSUE THREAD

**Issue by TheCry** [mahendrapaipuri/grafana-dashboard-reporter-app#189]
I have now tried everything to convert the date into a German date. Unfortunately I can't do that and hope that you can give me a tip
![image](https://github.com/user-attachments/assets/f7e5c17d-f502-4e74-a6eb-799221e4e73f)

The date should look like this:
Fr 29 Nov 2024, 10:42 AM
or simply:
29.10.2024, 10:42

**Comment by mahendrapaipuri** [comment]
Hello @TheCry 

Currently it is not possible to format date time in the report. But this should be fairly easy to implement. I will do it and make a new release soon
