### ISSUE TITLE
Modifying the output of generated report

### ISSUE THREAD

**Issue by Alan1810** [mahendrapaipuri/grafana-dashboard-reporter-app#19]
Hi @mahendrapaipuri,

Is there a way to modify the output ? 

For example, the number of page is present at the bottom of each page and in the dashboard title.

Regards

**Comment by mahendrapaipuri** [comment]
> For example, the number of page is present at the bottom of each page and in the dashboard title.

I am not quite sure if I understand you well. Normally the page number and total number of pages are calculated automatically based on the PDF by `chromium`. What exactly you would like to modify?

For the moment, there is no way to customize the format of the report. [Here](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/pkg/plugin/templates/report.gohtml) is the HTML template that is used to generate report. I tried to use the same format that the official plugin in Grafana Enterprise version uses in their reports.

**Comment by Alan1810** [comment]
For our need, we only want to have Dashboard title without the number of page in title of generated pdf report. The page number/Total page is already present as the bottom of the generated pdf report

**Comment by mahendrapaipuri** [comment]
I see. Just out of curiosity, is it a big blocker for you? I agree that page numbers are already present in the page footer and including them in the title is not _really_ necessary. However, having them in title is also more clear and as I said, I tried to adopt the template from enterprise plugin as much as I can and it does generate page numbers in the title.

It would be nice to make the header and footer of the report configurable. But that requires a bit of knowledge of HTML and CSS from the end users. If we make them configurable does it solve your issue? For instance, here is the [header](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/pkg/plugin/templates/header.gohtml) and [footer](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/pkg/plugin/templates/footer.gohtml) that plugin uses. Maybe we can make `content-header` and `content-footer` divs configurable.
