### ISSUE TITLE
Issue with Report Time Range in Grafana Dashboard Reporter

### ISSUE THREAD

**Issue by Jantores-bre** [mahendrapaipuri/grafana-dashboard-reporter-app#196]
I’m currently using the Grafana Dashboard Reporter plugin and am encountering an issue with the time range in the generated reports. Despite selecting a specific time range on the dashboard, the generated report always seems to include data only for the past hour.

I have verified that the time range is correctly set on the dashboard.
Confirmed that the dashboard displays the expected data for the chosen time range.
Generated the report using the plugin, but it consistently includes only the past hour's data.
Could this be related to the plugin configuration or an API issue?

Here’s some additional information about my setup:

Grafana Version: 11.2.2
Plugin Version: 1.7.0

![image](https://github.com/user-attachments/assets/1e70534b-b088-4f9b-8465-fb551b0e162c)
![image](https://github.com/user-attachments/assets/e8a8f75a-a91f-443a-80ab-1e2bc192e86e)

**Comment by mahendrapaipuri** [comment]
Hello @Jantores-bre 

Are you sure that you are passing `from` and `to` query parameters to report API? Could you please share the full URL that you are using to generate the report (redacting any sensitive info)?

Cheers

**Comment by mahendrapaipuri** [comment]
Most straight-forward and easiest approach would be to create a [Dashboard Link](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/manage-dashboard-links/). You can create a Dashboard Link, say `Create Report` following these [instructions in docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#using-grafana-web-ui). By checking the box `Include current time range` when creating link, report API will be called with the current selected time range.

If you need an example, add [this sample dashboard from the repo](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/dashboards/test-dashboard-collapsed.json) in your Grafana instance and you will see a `Report` link in top right corner. You can inspect the link details in the dashboard to understand how it is being done.

Let me know if that works for your case.

**Comment by Jantores-bre** [comment]
Thank you for the response and for pointing me towards the Dashboard Link approach. I'll try this and check how it works for our use case.

I also have a follow-up question regarding best practices for using localhost instead of an IP address in the URL.
Some of our customers operate with different VPN solutions, and relying on an IP address in the URL often creates conflicts when we need to make changes or test the solution.
Would you recommend any specific setup or approach to make the URL more dynamic and avoid IP dependency? For instance, is there a way to reliably use localhost or another standard in such environments?


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***




Fra: Mahendra Paipuri ***@***.***>
Sendt: mandag 9. desember 2024 17:07
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


Most straight-forward and easiest approach would be to create a Dashboard Link<https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/manage-dashboard-links/>. You can create a Dashboard Link, say Create Report following these instructions in docs<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#using-grafana-web-ui>. By checking the box Include current time range when creating link, report API will be called with the current selected time range.

If you need an example, add this sample dashboard from the repo<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/dashboards/test-dashboard-collapsed.json> in your Grafana instance and you will see a Report link in top right corner. You can inspect the link details in the dashboard to understand how it is being done.

Let me know if that works for your case.

-

**Comment by Jantores-bre** [comment]
I just found out by using this approach:
/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx

I have another question regarding the generated reports.
Is it possible to handle pagination for tables in the reports?
It would be great if the reports could dynamically handle table pagination, ensuring that data is presented across multiple pages without requiring pre-configured static layouts in the dashboard.

Is this functionality supported, or are there any workarounds you would recommend?


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***





Fra: Jan Tore Kallmyr
Sendt: tirsdag 10. desember 2024 10:35
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>; mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Mention ***@***.***>
Emne: SV: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)

Thank you for the response and for pointing me towards the Dashboard Link approach. I'll try this and check how it works for our use case.
I also have a follow-up question regarding best practices for using localhost instead of an IP address in the URL.
Some of our customers operate with different VPN solutions, and relying on an IP address in the URL often creates conflicts when we need to make changes or test the solution.
Would you recommend any specific setup or approach to make the URL more dynamic and avoid IP dependency? For instance, is there a way to reliably use localhost or another standard in such environments?

Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***




Fra: Mahendra Paipuri ***@***.******@***.***>>
Sendt: mandag 9. desember 2024 17:07
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.******@***.***>>
Kopi: Jan Tore Kallmyr ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


Most straight-forward and easiest approach would be to create a Dashboard Link<https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/manage-dashboard-links/>. You can create a Dashboard Link, say Create Report following these instructions in docs<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#using-grafana-web-ui>. By checking the box Include current time range when creating link, report API will be called with the current selected time range.

If you need an example, add this sample dashboard from the repo<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/dashboards/test-dashboard-collapsed.json> in your Grafana instance and you will see a Report link in top right corner. You can inspect the link details in the dashboard to understand how it is being done.

Let me know if that works for your case.

-

**Comment by mahendrapaipuri** [comment]
> I also have a follow-up question regarding best practices for using localhost instead of an IP address in the URL.
Some of our customers operate with different VPN solutions, and relying on an IP address in the URL often creates conflicts when we need to make changes or test the solution.

I am not quite sure I understand your set up here. But I guess you figured out that using relative URL like `/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx` solved your problem?

> Is it possible to handle pagination for tables in the reports?

By default plugin includes only table panel "picture" in the report. So, you get to see only the data that is visible in the panel. However, **it is possible to include raw data of the table panels at the end of the report**. You need to pass the panel IDs of the tabular panels and to the query parameter `includePanelDataID` to include data of those panels. Details here in the [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#rendering-tabular-data-in-the-report). For instance if the panel having tabular data has ID 5, your URL must be `/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx&includePanelDataID=5`. You can just repeat the query parameter for multiple panels.

Is that what you are looking for?

**Comment by Jantores-bre** [comment]
Hi.
It works with the relative URL 😊

Regarding table panels:
I see that it works well to include the Panel ID in the URL, and the raw data is correctly added to the end of the report.
However, one challenge I’m facing is that I would like to display tables under a "Panel" in the main part of the report, but I notice that they are only generated at the end of the report. This creates duplication where the tables appear both in their original form and again as raw data in the appendix.

Is there a way to hide the original table panels in the main report while still including their raw data in the appendix? Ideally, this would allow for a cleaner report layout without duplicating the tables.


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***




Fra: Mahendra Paipuri ***@***.***>
Sendt: tirsdag 10. desember 2024 11:29
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


I also have a follow-up question regarding best practices for using localhost instead of an IP address in the URL.
Some of our customers operate with different VPN solutions, and relying on an IP address in the URL often creates conflicts when we need to make changes or test the solution.

I am not quite sure I understand your set up here. But I guess you figured out that using relative URL like /api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx solved your problem?

Is it possible to handle pagination for tables in the reports?

By default plugin includes only table panel "picture" in the report. So, you get to see only the data that is visible in the panel. However, it is possible to include raw data of the table panels at the end of the report. You need to pass the panel IDs of the tabular panels and to the query parameter includePanelDataID to include data of those panels. Details here in the docs<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#rendering-tabular-data-in-the-report>. For instance if the panel having tabular data has ID 5, your URL must be /api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx&includePanelDataID=5. You can just repeat the query parameter for multiple panels.

Is that what you are looking for?

**Comment by mahendrapaipuri** [comment]
> It works with the relative URL 😊

Glad it works!!

> Is there a way to hide the original table panels in the main report while still including their raw data in the appendix? Ideally, this would allow for a cleaner report layout without duplicating the tables.

Yes, you can exclude panels in the report using `excludePanelID` query parameter. In my earlier example, the URL would be `api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx&includePanelDataID=5&excludePanelID=5`. Although I never tested them together, it should work. Please let me know if it does not.

**Comment by Jantores-bre** [comment]
Another issue I’ve noticed is that "Overrides" and "Units" from the tables are not included in the raw data.
I assume we’ll need to adjust the raw data manually to make it presentable. While this works, it does feel like a compromise.

Additionally, I’ve tried using the excludePanelID parameter in combination with includePanelDataID, but it doesn’t seem to work as expected. Even minimizing the tables down to a single line in the main report does not resolve the issue. It appears that both the original and raw data tables need to be visible at the same time.


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***




Fra: Mahendra Paipuri ***@***.***>
Sendt: tirsdag 10. desember 2024 11:58
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


It works with the relative URL 😊

Glad it works!!

Is there a way to hide the original table panels in the main report while still including their raw data in the appendix? Ideally, this would allow for a cleaner report layout without duplicating the tables.

Yes, you can exclude panels in the report using excludePanelID query parameter. In my earlier example, the URL would be api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=xxxxxxxxxx&includePanelDataID=5&excludePanelID=5. Although I never tested them together, it should work. Please let me know if it does not.

**Comment by mahendrapaipuri** [comment]
> Another issue I’ve noticed is that "Overrides" and "Units" from the tables are not included in the raw data.
I assume we’ll need to adjust the raw data manually to make it presentable. While this works, it does feel like a compromise.

The data included in the report is exactly the same CSV data that you can download from panel. Rest of the stuff like Units and Overrides are from the frontend magic which cannot be easily fetched.

 > Additionally, I’ve tried using the excludePanelID parameter in combination with includePanelDataID, but it doesn’t seem to work as expected. Even minimizing the tables down to a single line in the main report does not resolve the issue. It appears that both the original and raw data tables need to be visible at the same time.

I confirm this behaviour and this is a bug. I will fix it and make a release ASAP. Thanks for the test

**Comment by mahendrapaipuri** [comment]
> If there’s anything else you’d like me to test or provide feedback on, just let me know. I’ll be working quite a bit with this in the future with different scenarios.

Thanks a lot. Yes, once I put up a PR, I will let you know so that you can test it on your instance.

**Comment by mahendrapaipuri** [comment]
@Jantores-bre I put up a PR to fix the panel filtering. Could you please test it? You can download the plugin artifacts [here](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/actions/runs/12274245354)

**Comment by Jantores-bre** [comment]
Thank you.
I have a deadline now, so I won't be able to test this in production. However, I will test it in our test environment at the earliest opportunity.
Could you please send me a simple installation guide for this?


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***



Fra: Mahendra Paipuri ***@***.***>
Sendt: onsdag 11. desember 2024 11:50
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


@Jantores-bre<https://github.com/Jantores-bre> I put up a PR to fix the panel filtering. Could you please test it? You can download the plugin artifacts here<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/actions/runs/12274245354>

-

**Comment by mahendrapaipuri** [comment]
@Jantores-bre Ok, thanks. 

I will merge it into the main and then you can install the `nightly` version directly. You will find instructions in [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#installation-via-grafana-cli) on how to install `nightly` version.

**Comment by mahendrapaipuri** [comment]
> When I assign permissions to a team at the folder level, the dashboards within that folder do not seem to inherit the permissions as expected.

I confirm this behaviour. Well, seems like the user permissions list do not have inherited permissions and so, the check fails. This is going to be quite tricky to implement. I will think about it and see if I can come up with a solution!

**Comment by Jantores-bre** [comment]
Hi there.

Great!
I will test this as soon as possible.

Best regards

Jan Tore

Fra: Mahendra Paipuri ***@***.***>
Sendt: mandag 16. desember 2024 09:56
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


@Jantores-bre<https://github.com/Jantores-bre> I hope that I have fixed the issue with inherited permissions on folder. I have added e2e tests in CI for those scenarios and it seems to be working. Could you please test it out? You can get the new version by installing nightly release<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#installation-via-grafana-cli>

-

**Comment by Jantores-bre** [comment]
Hi there.

I am experiencing issues generating PDF reports using the Dashboard Reporter app in Grafana.
The logs indicate a certificate verification error when the plugin tries to access our Grafana instance at https://cloud.xxxxx.no
However, API requests using a Bearer token work without any issues, which makes me wonder if the problem is actually certificate-related or if it's caused by something else.

Here's a summary of the issue:


  *   The API key works fine, and I can retrieve dashboard data via API calls without problems.
  *   However, when trying to generate a PDF report, the plugin logs an error similar to:
"failed to get dashboard JSON model: tls: failed to verify certificate: x509: certificate signed by unknown authority"


  *   Our certificate is issued by GlobalSign GCC R6 AlphaSSL CA 2023, and we have ensured that the necessary CA certificates are installed on the system.
  *   Running openssl s_client -connect cloud.redox.no:443 -CApath /etc/ssl/certs still returns:
"verify error:num=21:unable to verify the first certificate

The issue only occurs when generating reports; regular access to Grafana via the browser and API calls work fine.

Before I continue troubleshooting the certificate trust, could you confirm if this is indeed a certificate validation issue on your plugin's side? Or could there be another underlying problem causing the report generation to fail?

Any guidance would be greatly appreciated!

Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***

**Comment by mahendrapaipuri** [comment]
I guess the browser and the host from where you are making API requests recognize your CA but not the server where Grafana is deployed. As plugin makes API requests using the CA bundle on the Grafana server, it can happen that these requests fail.

I recommend you to configure the plugin to [Skip TLS Check](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#additional-settings).

PS: Please dont comment on closed issues, it is hard to find these comments. APpreciate it if you can open a new issue if problem still persists. Cheers!

**Comment by Jantores-bre** [comment]
Hi,
Is there any risk associated with skipping the TLS check, or is this only a local issue on the PC?
Would there be any security implications, or is it simply a matter of how the CA is recognized by the Grafana server?


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***



Fra: Mahendra Paipuri ***@***.***>
Sendt: tirsdag 4. februar 2025 14:29
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


I guess the browser and the host from where you are making API requests recognize your CA but not the server where Grafana is deployed. As plugin makes API requests using the CA bundle on the Grafana server, it can happen that these requests fail.

I recommend you to configure the plugin to Skip TLS Check<https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#additional-settings>.

PS: Please dont comment on closed issues, it is hard to find these comments. APpreciate it if you can open a new issue if problem still persists. Cheers!

-

**Comment by mahendrapaipuri** [comment]
> Is there any risk associated with skipping the TLS check, or is this only a local issue on the PC?

There is always a small security implication when you ignore TLS check. If you do not want to skip TLS check, you can add your root CA to the system defaults that Go will load. You can find the locations where Go checks for root CAs [here](https://go.dev/src/crypto/x509/root_linux.go).

If your Grafana server is available on localhost (by default it runs on localhost:3000), you can point the `appUrl` in the plugin config to `http://localhost:3000` and plugin will make API requests via `localhost` which should be the most secure way.

**Comment by Jantores-bre** [comment]
Hi.

What We Tried:
Skip TLS Check (skipTlsCheck = true)
Set both GF_REPORTER_PLUGIN_SKIP_TLS_CHECK=true and skipTlsCheck = true in grafana.ini, but the plugin still tries to verify TLS and fails with:
tls: failed to verify certificate: x509: certificate signed by unknown authority

Use localhost (appUrl = http://localhost:3000)
Set appUrl = http://localhost:3000 in grafana.ini and GF_REPORTER_PLUGIN_APP_URL=http://localhost:3000, but the plugin still calls https://cloud.xxxxx.no instead of localhost.

Questions:
Is there a way to force the plugin to use localhost for API calls?
Why does skipTlsCheck = true seem to have no effect?


Med vennlig hilsen / Best regards

Jan Tore Kallmyr | Digitalization and Software Engineer
M: +47 97133221
E : ***@***.******@***.***>
W: www.bredigital.no<http://www.bredigital.no/>
Eidetorget 1
6490 Eide

***@***.***




Fra: Mahendra Paipuri ***@***.***>
Sendt: onsdag 5. februar 2025 09:23
Til: mahendrapaipuri/grafana-dashboard-reporter-app ***@***.***>
Kopi: Jan Tore Kallmyr ***@***.***>; Mention ***@***.***>
Emne: Re: [mahendrapaipuri/grafana-dashboard-reporter-app] Issue with Report Time Range in Grafana Dashboard Reporter (Issue #196)


Is there any risk associated with skipping the TLS check, or is this only a local issue on the PC?

There is always a small security implication when you ignore TLS check. If you do not want to skip TLS check, you can add your root CA to the system defaults that Go will load. You can find the locations where Go checks for root CAs here<https://go.dev/src/crypto/x509/root_linux.go>.

If your Grafana server is available on localhost (by default it runs on localhost:3000), you can point the appUrl in the plugin config to http://localhost:3000 and plugin will make API requests via localhost which should be the most secure way.

**Comment by mahendrapaipuri** [comment]
@Jantores-bre Could you please open a new issue? It will be easy to follow up! Thanks in advance!
