### ISSUE TITLE
Error generating report when specific time range is selected

### ISSUE THREAD

**Issue by soursing** [mahendrapaipuri/grafana-dashboard-reporter-app#199]
Hi,

We're getting error when generating reports when specific time range is selected from Grafana time picker. However pdf generation work properly when time is selected from the time picker drop down.

Eg: 
![image](https://github.com/user-attachments/assets/01543385-f467-42fa-9239-0539f817473a)

It looks like plugin is unable to parse the selected time.

**Error**: logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-12-11T16:35:58.533641755Z level=error msg="error generating report" pluginId=mahendrapaipuri-dashboardreporter-app endpoint=callResource err="error generating HTML file for dashboard XXXXXX: error executing Header template: template: header.gohtml:36:64: executing \"header.gohtml\" at <.From>: error calling From: 2024-12-03T18:30:00.000Z is not a recognised time format"

Grafana Version: 11.3.0
Plugin Version: 1.7.0

let me know if you need any more information.

**Comment by mahendrapaipuri** [comment]
Hello @soursing 

Thanks for reporting this. I can confirm this bug in Grafana v11.3.0 where `to` and `from` query parameters in the browser URL have changed from unix timestamp to datetime string when selecting absolute time.

I will put up a fix soon!

**Comment by mahendrapaipuri** [comment]
@soursing Could you please try the [nightly](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#installation-via-grafana-cli) version and report if the bug has been fixed?

Cheers

**Comment by soursing** [comment]
@mahendrapaipuri thanks for providing quick fix. It is working now.
When are you planning to release the next version?

**Comment by mahendrapaipuri** [comment]
Cheers!! 

I hope very soon. There is one more issue that I would like to fix before making a release.
