### ISSUE TITLE
Panel Not Found Error

### ISSUE THREAD

**Issue by stevendaniel1** [mahendrapaipuri/grafana-dashboard-reporter-app#204]
Hi, i enabled all the settings marked by the guide , but the reporter gave me this error 
<img width="252" alt="111" src="https://github.com/user-attachments/assets/9dadb7c7-da6b-44a8-9e8b-403f7cd0a9b0" />
<img width="600" alt="2222" src="https://github.com/user-attachments/assets/d2a04adc-52a1-4c10-8896-cbc7dd695012" />

this is the link what am using in the dashboard gui
localhost:3000/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=de1d1gog0c0zke

**Comment by stevendaniel1** [comment]
And they had all permision in the api, the dashboard and  the service account

**Comment by mahendrapaipuri** [comment]
Hello @stevendaniel1 

Which version of plugin and Grafana are you using? Which OS?

Could you also please share the Grafana logs?

Cheers

**Comment by stevendaniel1** [comment]
> Hello @stevendaniel1
> 
> Which version of plugin and Grafana are you using? Which OS?
> 
> Could you also please share the Grafana logs?
> 
[grafana.log](https://github.com/user-attachments/files/18149673/grafana.log)

> Cheers

Hi, i am using grafana 11.03 and Windows,

**Comment by stevendaniel1** [comment]
Hello, greetings. I have attached everything you need in your response.

**Comment by stevendaniel1** [comment]
I'm going to try it on my Ubuntu system and try it

Cheers

**Comment by stevendaniel1** [comment]
Hi 
![image](https://github.com/user-attachments/assets/cff01377-71dd-4cde-ba90-c56b217e9d50)

The same error persist, am using ubuntu 24.10, and the same version of plugin
this is my log

help ):

[grafana log.txt](https://github.com/user-attachments/files/18151617/grafana.log.txt)

**Comment by mahendrapaipuri** [comment]
Thanks @stevendaniel1 for the tests and logs

This is helpful, at least I will able to reproduce it. Which version of Grafana are you using? 11.0.3 or 11.3.0? And how did you install chromium? From `apt` or `snap`?

**Comment by stevendaniel1** [comment]
Grafana  11.03.1

I am using cromium 131.0.6778 official build snap 64 bits

**Comment by mahendrapaipuri** [comment]
Ok, thanks for the details.

I might have found something. The plugin uses the chromium shipped by `grafana-image-renderer` when found. But that chrome is a standalone packaged version which still needs a lot of runtime dependencies. The [docs](https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/troubleshooting/) states which dependencies are needed for different distros. If you visit the status page of the plugin at `<Grafana HOST>/a/mahendrapaipuri-dashboardreporter-app/status` you should see the errors about missing dependencies. Once I installed the dependencies, the plugin started as expected. Here are the list of dependencies that I installed:

```
apt-get install libx11-6 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrender1 libxtst6 libglib2.0-0 libnss3 libcups2  libdbus-1-3 libxss1 libxrandr2 libgtk-3-0 libasound2t64 libxcb-dri3-0 libgbm1 libxshmfence1
```

Could you try it and see if it works? If it is indeed the case, we should improve the error handling and show it on server logs.

**Comment by stevendaniel1** [comment]
![Captura desde 2024-12-16 11-38-08](https://github.com/user-attachments/assets/f6a34290-89df-4dfc-a4bf-c83988082e8d)

well, this is my console and they had all the dependences upgraded, updated and installed

and this is my plugin check panel 

![Captura desde 2024-12-16 11-38-19](https://github.com/user-attachments/assets/bac02e5b-02f7-456d-80b1-325539f1346a)

**Comment by stevendaniel1** [comment]
Good News!

![image](https://github.com/user-attachments/assets/3224c17f-725a-464b-8ef0-cbb83fa0c16f)

I installed the nightly version and i set all in the grafana.ini, and works

thanks for your support!

Now one last question, I want to install this plugin in balena os, what do you personally recommend, that I use the docker version or can I directly enter the grafana-cli and install it directly there, modifying all the files?

I listen to your recommendation

**Comment by mahendrapaipuri** [comment]
> I installed the nightly version and i set all in the grafana.ini, and works

Thats awesome news. I ll cut a release out of `main` soon.

> Now one last question, I want to install this plugin in balena os, what do you personally recommend, that I use the docker version or can I directly enter the grafana-cli and install it directly there, modifying all the files?

I dont have any experience with Balena but I understand the OS is optimized for Docker containers. If you are going to deploy Grafana in docker container, I guess the _only_ option is to include plugin artifacts with a bind mount, isnt it? Because even if you install plugin inside Grafana container using `grafana-cli`, I think you will need to restart Grafana process after plugin installation which you cant as it is going to be PID 1. Installng a plugin is nothing but extracting plugin artifacts at `/var/lib/grafana/plugins/<plugin_name>`. So, you can download the plugin artifacts on the host and bind mount that directory to `/var/lib/grafana/plugins/mahendrapaipuri-dashboardreporter-app`. 

Maybe there are better ways to do it but this is what I can think of.

**Comment by stevendaniel1** [comment]
> > I installed the nightly version and i set all in the grafana.ini, and works
> 
> Thats awesome news. I ll cut a release out of `main` soon.
> 
> > Now one last question, I want to install this plugin in balena os, what do you personally recommend, that I use the docker version or can I directly enter the grafana-cli and install it directly there, modifying all the files?
> 
> I dont have any experience with Balena but I understand the OS is optimized for Docker containers. If you are going to deploy Grafana in docker container, I guess the _only_ option is to include plugin artifacts with a bind mount, isnt it? Because even if you install plugin inside Grafana container using `grafana-cli`, I think you will need to restart Grafana process after plugin installation which you cant as it is going to be PID 1. Installng a plugin is nothing but extracting plugin artifacts at `/var/lib/grafana/plugins/<plugin_name>`. So, you can download the plugin artifacts on the host and bind mount that directory to `/var/lib/grafana/plugins/mahendrapaipuri-dashboardreporter-app`.
> 
> Maybe there are better ways to do it but this is what I can think of.

Thanks for your support! great project and very helpfull

ill try your suggestions
