### ISSUE TITLE
Discrepancy in Release Tag Naming Convention Causes Installation Script Failure

### ISSUE THREAD

**Issue by rgarmyn** [mahendrapaipuri/grafana-dashboard-reporter-app#21]
Hi @mahendrapaipuri ,

I encountered an issue while trying to install the Grafana Dashboard Reporter plugin using the provided shell script [`bootstrap-dashboard-reporter-app.sh`](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/0a5c4f367d65386bf0a645651d6437320ac2bfc6/scripts)
 The script attempts to download the latest release of the plugin from the GitHub repository using a constructed URL that includes the release tag name.

The script assumes that the release tags are prefixed with a 'v' (e.g., 'v1.0.0'). However, the actual release tags in the repository do not include this prefix (e.g., '1.0.0'). 
I suggest updating the release tags in the repository to include the 'v' prefix.

**Comment by mahendrapaipuri** [comment]
Hello @rgarmyn Thanks for reporting. #22 should fix it.
