### ISSUE TITLE
"error generating report" when Grafana API exceed 30 seconds to respond

### ISSUE THREAD

**Issue by chiheb22** [mahendrapaipuri/grafana-dashboard-reporter-app#217]
as mentioned in the title i have some dashboards that takes time to get the time series. when the request exceed 30 seconds "error generating report" occur with 500 internalserver error.
grafana logs : `level=error msg="error generating report" err="error rendering PNGs in parallel for dashboard X : error executing request for Y : net/http: request canceled (Client.Timeout exceeded while awaiting headers)`
i tried to increase the timeout in "pkg/plugin/config/settings.go" 
```
HTTPClientOptions: httpclient.Options{
			Timeouts: &httpclient.TimeoutOptions{
				Timeout: 120 * time.Second,
			},
			TLS: &httpclient.TLSOptions{
				InsecureSkipVerify: false,
			},
```
but the moment i edit the plugin and install it, it stop working.

**Comment by mahendrapaipuri** [comment]
Hello @chiheb22 

An error like `level=error msg="error generating report" err="error rendering PNGs in parallel for dashboard X : error executing request for Y : net/http: request canceled (Client.Timeout exceeded while awaiting headers)` means that your plugin is not able to reach Grafana API. Can you post me logs to see at which address that the plugin is trying to reach Grafana API? If you did not configure anything, it will attempt to reach on `localhost:3000` on bare-metal deployments. If your Grafana is not reachable on this address, you need to set [`appUrl`](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/src/README.md#additional-settings) where Grafana API is reachable

**Comment by mahendrapaipuri** [comment]
Ok, I see. If it fails in the step where it fetches PNGs of panels, a quick fix would be to set `timeout: 120` in the provisioning config file of plugin and restart Grafana. So, a basic provisioning file would be as follows:

```
apiVersion: 1

apps:
  - type: mahendrapaipuri-dashboardreporter-app
    org_id: 1
    org_name: Main Org.
    disabled: false
    jsonData:
     timeout: 120 # in seconds
```

and it would set timeout as 120 seconds to HTTP client. This is not documented but I will do it as it can be useful. Could you try this approach and see if it works for your case?

**Comment by chiheb22** [comment]
yes it worked. thank you

**Comment by mahendrapaipuri** [comment]
Hello @jellyfinuser 

You need to install this file in the provisioned folder. By default Grafana uses `/etc/grafana/provisioning` as provisioning directtory and you will need to place that file as `/etc/grafana/provisioning/plugins/report.yaml`. By restarting Grafana, plugin will be automatically enabled and client timeout will be configured. There are more timeouts that you can configure which are documented in [README](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#advanced-settings)

**Comment by duchieu2k** [comment]
Hi @mahendrapaipuri, Do you have another way to configure timeout without editing provisioning file. Because I deploy grafana via K8s, anytime I update provisioning file, I must to restart Grafana pod

And can I set `timeout` as a global parameter for all orgs?
