### ISSUE TITLE
Failed to call resource

### ISSUE THREAD

**Issue by henjoe** [mahendrapaipuri/grafana-dashboard-reporter-app#23]
Hi I tried to input this in URL 
<grafanaAppUrl>/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report?dashUid=<UID of dashboard>
but returned an error:

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/49782655/73b9a08c-df01-40d3-a3a7-a3a8d89984bb)

Other question is, is there other way to enable this app outside the UI of grafana? 
`Apps > Dashboard Reporter App > Configuration`

Thanks and Regards for this great app!

**Comment by mahendrapaipuri** [comment]
Thanks for your interest @henjoe. 

I will need your Grafana server logs to understand why plugin hasn't registered itself with Grafana API. Some of the things you can check

- Ensure plugin is enabled from Grafana UI
- Whitelist the plugin in Grafana settings as instructed in [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#local-installation). By default Grafana does not load any unsigned plugins.

> Other question is, is there other way to enable this app outside the UI of grafana?
Apps > Dashboard Reporter App > Configuration

Yes, it is possible with provisiohttps://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/c4ff5f86a5a835a23c6738634af92389ce040ed6/provisioning/plugins/app.yaml#L7ning the plugin. Details can be found in [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#configuring-the-plugin). You will need to install a provisioned config file ([example file](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/plugins/app.yaml) can be found in repo) at `/etc/grafana/provisioning/plugins/reporter.yml` assuming you are using default Grafana provisioning folders. In YAML file, by setting [disable: false](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/c4ff5f86a5a835a23c6738634af92389ce040ed6/provisioning/plugins/app.yaml#L7), the plugin will be enabled by default.

**Comment by henjoe** [comment]
Thanks for this. 
To be honest, I just try it to run on grafana V9.0 if it will run, but seems like they have different in terms of UI compared to V10. I know that it requires V10 to use this plugin, I am just curious if it will run on V9.

**Comment by mahendrapaipuri** [comment]
I think provisioning should work with Grafana >=v7. You can try provisioning the plugin to enable it. I dont see why it should not work in v9.

**Comment by henjoe** [comment]
Thanks for this. I will try this and informed my testing!

Regards,

**Comment by henjoe** [comment]
Seems like the error is about my self-signed certificate:
`logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-04-08T20:19:20.0783352+04:00 level=error msg="error generating report" pluginID=mahendrapaipuri-dashboardreporter-app endpoint=callResource err="error fetching dashboard rv683NSIz: error executing request for https://localhost/api/dashboards/uid/rv683NSIz: Get \"https://localhost/api/dashboards/uid/rv683NSIz\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
logger=context userId=1 orgId=1 uname=admin t=2024-04-08T20:19:20.0812183+04:00 level=error msg="Request Completed" method=GET path=/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report status=500 remote_addr=127.0.0.1 time_ms=76 duration=76.21ms size=24 referer= handler=/api/plugins/:pluginId/resources/*
logger=context userId=0 orgId=0 uname= t=2024-04-08T20:19:20.8616311+04:00 level=info msg="Request Completed" method=GET path=/favicon.ico status=302 remote_addr=127.0.0.1 time_ms=1 duration=1.8244ms size=29 referer= handler=public-assets
`

**Comment by henjoe** [comment]
But I already set in the reporter.yaml settings:

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/49782655/100300d4-8e9d-46a7-b120-cbab3eca6c18)

**Comment by mahendrapaipuri** [comment]
Thanks a lot for testing. Could you please share complete logs? 

The plugin will output the provisioned config at the beginning. I would like to see those lines to ensure if provisioned config is properly taken into account. 

Thanks in advance.
