### ISSUE TITLE
google-chrome not found

### ISSUE THREAD

**Issue by sruputway** [mahendrapaipuri/grafana-dashboard-reporter-app#27]
hello,

I've issue when generate pdf, grafana running on docker together with image-render, I put screenshot on the attachment and following is version detail
- Grafana docker version                                                      = grafana:10.4.2-ubuntu
- Grafana docker Image Render version                               = grafana-image-renderer:3.10.3
- Grafana Plugin grafana-dashboard-reporter-app version = v1.2.0
- Grafana Plugin Image Render version                               = grafana-image-renderer:3.10.3
- Grafana Plugin 

I run docker with following this docker-compose https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app.

![Docker_Desktop_1LDgL1eUMy](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/15627316/16fe6f23-df15-42d0-b207-ee2ab30ef035)

**Comment by mahendrapaipuri** [comment]
I guess you are not using the same Grafana docker image as provided in the repo. If you are using your own Grafana image, you will need to install `chromium` in the image. For example, we do it for the image provided in the repo [here](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/d7d6e06ef7846a9e8274ef006212b8c723d124c9/.config/Dockerfile#L16-L17)
