### ISSUE TITLE
How to obtain logs

### ISSUE THREAD

**Issue by jkroepke** [mahendrapaipuri/grafana-dashboard-reporter-app#40]
Hi all,

thank for providing this plugins.

I'm running Grafana with the image-renderer plugin on our Kubernetes instances. I installed the plugin and can see the plugin on the admin ui.

If I'm open the report endpoint, I'm getting this:

```
{
    "message": "An error occurred within the plugin",
    "messageId": "plugin.downstreamError",
    "statusCode": 500,
    "traceID": ""
}
```

Logs from grafana:

```
{"config":"Grafana App URL: ; Skip TLS Check: false; Grafana Data Path: /var/lib/grafana; Orientation: portrait; Layout: simple; Dashboard Mode: full; Time Zone: Europe/Berlin; Encoded Logo: ; Max Renderer Workers: 2; Persist Data: false; Included Panel IDs: all; Excluded Panel IDs: none","endpoint":"callResource","level":"info","logger":"plugin.mahendrapaipuri-dashboardreporter-app","msg":"provisioned config","pluginID":"mahendrapaipuri-dashboardreporter-app","t":"2024-06-04T15:39:21.849170133Z"}
{"duration":"4.191834ms","handler":"/api/plugins/:pluginId/resources/*","level":"error","logger":"context","method":"GET","msg":"Request Completed","orgId":1,"path":"/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report","referer":"","remote_addr":"192.168.49.1","size":116,"status":500,"status_source":"downstream","t":"2024-06-04T15:39:21.8495103Z","time_ms":4,"uname":"joe@company.de","userId":2}
```

Anything else to observe?

**Comment by mahendrapaipuri** [comment]
Hello @jkroepke Thanks for your interest.

Did you provision the plugin according to [docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#configuring-the-plugin). It seems the `appUrl` in the config is missing and that is probably the reason why you see this `plugin.downstreamError`. If your turn on debugging on Grafana server, you will get more logs.

**Comment by jkroepke** [comment]
Hi @mahendrapaipuri 

I read the docs, but I didn't not configure the app url.

> appUrl: The URL at which Grafana is running. By default, http://localhost:3000 is used which should work for most of the deployments. If environment variable GF_APP_URL is set, that will take the precedence over the value configured in the provisioning file.

The default value should work, but it seem that no default is set?

**Comment by mahendrapaipuri** [comment]
Unfortunately there is no default value for appUrl. It is compulsory to provide the config file at least with appUrl. 

Could you try provisioning the plugin with a config file with appUrl set?

**Comment by mahendrapaipuri** [comment]
Seems like there is no native way to provision plugins from helm chart. You can try setting an env var GF_APP_URL on Grafana server and plugin should pick it up.

**Comment by mahendrapaipuri** [comment]
When users run Grafana server using non default server settings and do not provision plugin, hard coding default URL will end up in misleading errors. Actually we should emit an error log [here](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/88d0c230b07ce19f896a6960935ca1a55e7cd959/pkg/plugin/app.go#L211) as Grafana server is not showing up the returned error.

**Comment by jkroepke** [comment]
May ask my-self in which scenario localhost:3000 doesn't fit.

**Comment by jkroepke** [comment]
Btw, I figure out that `GF_APP_URL` is only set, if an plugin has an "external service"? Not sure, what is exactly means. 

https://github.com/grafana/grafana/blob/9f9928d41a9a56e7743a7106b88bce176bd8d402/pkg/services/pluginsintegration/pluginconfig/envvars.go#L54

Thats could be the reason, why the env variable is not set at my instance. 

The suggest workaround with setting the environment variable from outside may work, util grafana implement that: https://github.com/grafana/grafana/issues/74316

While I think everything is fine now, it could be break in the future.

**Comment by mahendrapaipuri** [comment]
> Btw, I figure out that GF_APP_URL is only set, if an plugin has an "external service"? Not sure, what is exactly means.

Yes, when external accounts is enabled, Grafana server will set up `GF_APP_URL` on plugin process. This is for the plugin to request a service account API token from Grafana server. 

But all the environment variables with prefix `GF_*` are supposed to be passed by the end user. It is a way to [override configuration in config file](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables). 

Take away here is: User needs to tell the plugin at which URL Grafana is accessible either by provisioning the plugin config or by passing env var `GF_APP_URL`. 

You are right about the issue you mentioned here. If and when that is implemented and merged, it will no longer possible to pass Grafana app URL via env var. In that case we should clearly document that.

**Comment by jkroepke** [comment]
@mahendrapaipuri I may have to ask again, to I can obtain the debug logs of the plugin?

I'm running grafana on debug, but if I run the render endpoint, I just got this:

> {"endpoint":"callResource","err":"error rendering PDF: Printing failed (-32000)","level":"error","logger":"plugin.mahendrapaipuri-dashboardreporter-app","msg":"error generating report","pluginID":"mahendrapaipuri-dashboardreporter-app","t":"2024-06-04T21:18:30.449635304Z"}

**Comment by mahendrapaipuri** [comment]
The plugin uses the same context logger as Grafana, so when we enable debug logging in Grafana, plugin should emit debug logs too. You should definitely get more logs.

That error seems to me that chromium failed to generate PDF from the web page. How did you add chromium in your Grafana image? The developmental image that the repo uses for testing uses alpine Linux and and we [install chromium here using `apk`](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/88d0c230b07ce19f896a6960935ca1a55e7cd959/.config/Dockerfile#L17)

**Comment by jkroepke** [comment]
Yes, chrome is installed and I can observe chrome processes on the container.

**Comment by mahendrapaipuri** [comment]
Could you share your custom image's Dockerfile? If the shared libs are missing for chrome, these errors can pop up.

**Comment by jkroepke** [comment]
At least I do a `ldd chromium` on the binary and I miss no shared library.

**Comment by mahendrapaipuri** [comment]
Unless I get to know more details about your env, it is very hard to find the issue.

**Comment by jkroepke** [comment]
> Unless I get to know more details about your env, it is very hard to find the issue.

I feel the same.

Efficiently, I only see the error from the chromedp library that you are using:

https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/88d0c230b07ce19f896a6960935ca1a55e7cd959/pkg/plugin/report.go#L338

I feel that the chromedp library may provide too less issues.

I guess to indicate the error, the stderr from chrome proccess itself would be nice, but I guess the chromedp library does not provide this.

**Comment by mahendrapaipuri** [comment]
Could you try with Dockerfile [provided in the repo](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/.config/Dockerfile)?
