### ISSUE TITLE
Problem with download plugin

### ISSUE THREAD

**Issue by m4t1kmatik** [mahendrapaipuri/grafana-dashboard-reporter-app#44]
Hello, I have a problem after downloading plugin and restart Grafana in /var/log/grafana.log I have this message:
logger=plugins.signature.validation t=2024-07-01T12:10:13.396552752+03:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginId=mahendrapaipuri-dashboardreporter-app status=unsigned
logger=plugins.validation t=2024-07-01T12:10:13.397720071+03:00 level=error msg="Plugin validation failed" pluginId=mahendrapaipuri-dashboardreporter-app error="plugin 'mahendrapaipuri-dashboardreporter-app' has no signature"

My Grafana v.10.2.3

**Comment by mahendrapaipuri** [comment]
Hello,

Thank you for opening the issue.

As the plugin has not been officially signed by Grafana, you will have to let Grafana _allow_ the plugin. You will need to add following config to Grafana plugins section:

```
[plugins]
allow_loading_unsigned_plugins = mahendrapaipuri-dashboardreporter-app
```

Please look into [installation docs](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#local-installation) for more details

**Comment by m4t1kmatik** [comment]
I have this line in grafana.ini, 
`[plugins]
;enable_alpha = false
;app_tls_skip_verify_insecure = false
# Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never loaded.
;allow_loading_unsigned_plugins = mahendrapaipuri-dashboardreporter-app
# Enable or disable installing / uninstalling / updating plugins directly from within Grafana.
;plugin_admin_enabled = false
;plugin_admin_external_manage_enabled = false
;plugin_catalog_url = https://grafana.com/grafana/plugins/
# Enter a comma-separated list of plugin identifiers to hide in the plugin catalog.
;plugin_catalog_hidden_plugins =
# Log all backend requests for core and external plugins.
;log_backend_requests = false
# Disable download of the public key for verifying plugin signature.
; public_key_retrieval_disabled = false
# Force download of the public key for verifying plugin signature on startup. If disabled, the public key will be retrieved every 10 days.
# Requires public_key_retrieval_disabled to be false to have any effect.
; public_key_retrieval_on_startup = false
# Enter a comma-separated list of plugin identifiers to avoid loading (including core plugins). These plugins will be hidden in the catalog.
; disable_plugins =
`

**Comment by m4t1kmatik** [comment]
There is my /etc/grafana/grafana.ini:
![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/169524092/108f1c99-0829-44bb-b9b5-495354b434e1)

**Comment by mahendrapaipuri** [comment]
You will have to remove the leading `;` in the line. Grafana treats lines starting with `;` as comments.

**Comment by m4t1kmatik** [comment]
Yes, that was the mistake... Thank you very much
