### ISSUE TITLE
plugin DownStreamError

### ISSUE THREAD

**Issue by SanthoshKumar18245** [mahendrapaipuri/grafana-dashboard-reporter-app#49]
DEBUG[07-05|12:33:15] Sending query                            logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=prometheus dsUID=bdq0msrl7t69sf uname=admin start=2024-07-05T06:58:26.633Z end=2024-07-05T07:03:26.633Z step=15s query="probe_success{job=\"blackbox\", instance=\"http://183.82.242.154:85\"}"
DEBUG[07-05|12:33:19] Singleflight request for OAuth token sync logger=oauth_token.sync key=user:1
DEBUG[07-05|12:33:19] Expiration check has been cached, no need to refresh logger=oauthtoken userID=1
DEBUG[07-05|12:33:19] Using cached permissions                 logger=accesscontrol.service key=rbac-permissions-1-user-1
DEBUG[07-05|12:33:19] Matched scope                            logger=accesscontrol.evaluator user scope=plugins:* target scope=plugins:id:mahendrapaipuri-dashboardreporter-app
INFO [07-05|12:33:19] provisioned config                       logger=plugin.mahendrapaipuri-dashboardreporter-app endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app config="Grafana App URL: ; Skip TLS Check: false; Grafana Data Path: /root/home/observelite/reporter/observelite/data; Orientation: portrait; Layout: simple; Dashboard Mode: default; Time Zone: Asia/Kolkata; Encoded Logo: ; Max Renderer Workers: 2; Persist Data: false; Included Panel IDs: all; Excluded Panel IDs: none"
ERROR[07-05|12:33:19] Internal server error                    logger=context userId=1 orgId=1 uname=admin error="[plugin.downstreamError] client: failed to call resources: failed to receive call resource response: rpc error: code = Unknown desc = grafana app URL not found. Please set it in provisioned config" remote_addr=192.168.100.1 traceID=
ERROR[07-05|12:33:19] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/api/plugins/mahendrapaipuri-dashboardreporter-app/resources/report status=500 remote_addr=192.168.100.1 time_ms=24 duration=24.753233ms size=116 referer= handler=/api/plugins/:pluginId/resources/* status_source=downstream
DEBUG[07-05|12:33:20] No changes detected. Skip updating       logger=ngalert.scheduler
DEBUG[07-05|12:33:20] Rule is ready to run on the current tick logger=ngalert.scheduler uid=ddqpno89rcao0f tick=172016300 frequency=1
 offset=0
DEBUG[07-05|12:33:20] got secret value from cache              logger=secrets.kvstore orgId=1 type=datasource namespace=prometheus
DEBUG[07-05|12:33:20] Sending query                            logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=prometheus dsUID=bdq0msrl7t69sf uname=grafana_scheduler rule_uid=ddqpno89rcao0f org_id=1 start=2024-07-05T12:28:20+05:30 end=2024-07-05T12:33:20+05:30 step=15s query="probe_success{job=\"blackbox\", instance=\"http://14.194.138.90:85\"}"

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/d457facc-4aca-41fd-abe1-5556f21dbf70)

![image](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/assets/133011171/7ab53ad9-f532-4d23-b016-131e084bc85e)

**Comment by mahendrapaipuri** [comment]
> grafana app URL not found. Please set it in provisioned config

That is the error. Please try to read and understand the logs before spamming the issues.

**Comment by SanthoshKumar18245** [comment]
`/conf/provisioning/plugins# cat sample.yaml`
# # config file version
apiVersion: 1

# apps:
#   - type: grafana-example-app
#     org_name: Main Org.
#     disabled: true
#   - type: raintank-worldping-app
#     org_id: 1
#     jsonData:
#       apiKey: "API KEY"


Where do I need to add? is this the correct yaml file ?

**Comment by SanthoshKumar18245** [comment]
@mahendrapaipuri 
Sorry for ping you again and again but i have tried but not able solve the problem.

**Comment by mahendrapaipuri** [comment]
It is already mentioned in docs on [how to provision plugin config](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/tree/main/src#configuring-the-plugin). There is an example [config file](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/plugins/app.yaml) is also provided.

**Comment by SanthoshKumar18245** [comment]
Done. Thank you
