### ISSUE TITLE
Error while generating report

### ISSUE THREAD

**Issue by DoekT** [mahendrapaipuri/grafana-dashboard-reporter-app#60]
Hi!

I'm encountering two errors while trying to generate reports with the plugin

renderer_1  | {"column":6183,"level":"error","line":142,"message":"Browser console error","msg":"Moment Timezone found Etc/Unknown from the Intl api, but did not have that data loaded.","url":"http://grafana:3000/public/build/1247.34022e0fa8ad25da7b32.js"}

grafana     | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-07-31T20:27:07.050394088Z level=error msg="error generating report" endpoint=callResource err="error rendering PDF: exec: \"google-chrome\": executable file not found in $PATH" pluginID=mahendrapaipuri-dashboardreporter-app

I’ve deployed the application using docker-compose and have installed chromium-browser on the host system.

Could you help me resolve these issues?

Thank you in advance!

**Comment by mahendrapaipuri** [comment]
Hello,

> renderer_1 | {"column":6183,"level":"error","line":142,"message":"Browser console error","msg":"Moment Timezone found Etc/Unknown from the Intl api, but did not have that data loaded.","url":"[http://grafana:3000/public/build/1247.34022e0fa8ad25da7b32.js"}](http://grafana:3000/public/build/1247.34022e0fa8ad25da7b32.js%22%7D)

This is not fatal. You can ignore it.

> grafana | logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-07-31T20:27:07.050394088Z level=error msg="error generating report" endpoint=callResource err="error rendering PDF: exec: "google-chrome": executable file not found in $PATH" pluginID=mahendrapaipuri-dashboardreporter-app

This is the issue. You will need to install the `chromium` **inside** the container where Grafana is running. If you are using official Grafana images, you can [add chromium](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/6f6da02620170ad209005bc145d713c9f174404d/.config/Dockerfile#L17) to it.

**Comment by DoekT** [comment]
Hi,

By installing Chromium in the Dockerfile, the plugin works. I'm fairly new to docker, so I'm still learning. Thank you for the quick response.
