### ISSUE TITLE
Rendering multiple dashboard to a single PDF

### ISSUE THREAD

**Issue by Adrian-LSY** [mahendrapaipuri/grafana-dashboard-reporter-app#62]
Hi,
As the title states, does the app currently support generating a PDF from multiple dashboards?
Or perhaps sometime in the future?

**Comment by mahendrapaipuri** [comment]
Hello,

Thanks for rising this question.

Why not generate a separate report for each dashboard and then merge them with utility tools like `ghostscript`, `imagemagick`? PDF manipulation has never been an easy thing to manage and doing something inside plugin will make it less robust and more dependent on system libs.

**Comment by Adrian-LSY** [comment]
Got it.
I'd just like to know if there's something built in before I start using 3rd party tools.
