### ISSUE TITLE
Authentication by Cookie does not works

### ISSUE THREAD

**Issue by jkroepke** [mahendrapaipuri/grafana-dashboard-reporter-app#73]
It seems like the Cookie header from a API Request is ignored.

If externalServiceAccount feature is disabled and no token is set, then the error occurs that no app secret is given.

Plugin Version: 1.5.0 
Grafana Version: 11.1.3

**Comment by mahendrapaipuri** [comment]
Yes, this is expected. Check the [comment](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/057daf24be94a8b3aeda9a34570f65269ba47171/pkg/plugin/resources.go#L165-L172) in the src. 

README has been [updated](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/src/README.md#grafana-api-token) as well to clearly mention this behavior.

**Comment by jkroepke** [comment]
If externalServiceAccounts is enabled, can unauthorized users generated PDFs?

**Comment by mahendrapaipuri** [comment]
> If externalServiceAccounts is enabled or token is set, can unauthorized users generated PDFs?

Yes, a user who does not have permissions on a given dashboard will be able to generate report for it as the plugin always uses service account token to make requests. But #75 will fix it. Cheers for the PR.
