### ISSUE TITLE
Report panel element sizing issue

### ISSUE THREAD

**Issue by Adrian-LSY** [mahendrapaipuri/grafana-dashboard-reporter-app#92]
Hi, I've noticed a small issue with the pdf generation in a grid layout, refer to the pdf below

[report.pdf](https://github.com/user-attachments/files/16775568/report.pdf)

The right-most panels are always scaled down slightly compared to the panels towards the left.

I'm currently on plugin v1.4.1, Grafana v10.3.4

**Comment by mahendrapaipuri** [comment]
Hello @Adrian-LSY, could you please share the dashboard JSON model so that I can try to reproduce it? Cheers

**Comment by Petorus** [comment]
Hi @mahendrapaipuri, 

i encount the same issue.
Without any change on dashboard, i see change on panels size.
The change arrived between 28/08 and 29/08

I try to update your plugin and/or image-renderer, without any effect.

You can see the report as like i want in file 'good_report'.
In file 'bad_report', you can see the report like is now generated
[good_report.pdf](https://github.com/user-attachments/files/16991480/good_report.pdf)
[bad_report.pdf](https://github.com/user-attachments/files/16991481/bad_report.pdf)

I attach the dashboard JSON Model :
[Meteo de la plateforme de Production-1726219113108.json](https://github.com/user-attachments/files/16991514/Meteo.de.la.plateforme.de.Production-1726219113108.json)

I'm currently running this version 
- Grafana : v11.1
- Image Render Plugin : v3.11.4
- Grafana Dashboard Reporter : v1.6.1

**Comment by mahendrapaipuri** [comment]
Cheers @Petorus 

Your reports and dashboard model are very helpful. I clearly see the problem here. I ll try to debug it and push a fix ASAP.

We have refactored the plugin a lot recently and so, there are few regressions. I hope to fix it soon!!

**Comment by mahendrapaipuri** [comment]
#367 is a proposed fix. @Petorus could you please try with this patch? You can download plugin artifacts [here](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/actions/runs/10863383135/artifacts/1933278093)
